CREATE TABLE [dbo].[DataUsage]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
    [UserId] NVARCHAR(128) NOT NULL,
	[Platform] NVARCHAR(128) NOT NULL,
	[Application] NVARCHAR(128) NOT NULL,
	[DateUsed] DATETIME2 NOT NULL DEFAULT getutcdate(),
)
